### ISSUE TITLE
make win throws error

### ISSUE THREAD

**Issue by MarceloPaco** [BrendelGroup/GeneSeqer#4]
Hello, I've been trying to build this program from source for the windows 10 operating system and I have tried the command suggested in the documentation. Here are the following results:

> C:\Users\LabData\Documents\GitHub\GeneSeqer\src>make win
mkdir "../bin"
make[1]: Entering directory `C:/Users/LabData/Documents/GitHub/GeneSeqer/src'
make[1]:` *** No rule to make target `MakeArray.obj', needed by `MakeArray'.  Stop.
make[1]: Leaving directory `C:/Users/LabData/Documents/GitHub/GeneSeqer/src'
make: *** [win] Error 2

I was wondering if there is a solution to this problem?

~ Cheers

**Comment by vpbrendel** [comment]
Can't say that I have tried to compile this on Windows, let alone Windows 10. Linux works fine.
You probably need to look at what compiler you have installed and what its rules are. The Makefile is straightforward.

Volker

**Comment by vpbrendel** [comment]
A simple alternative these days is to fire up the Ubuntu app and run the code in the familiar Linux environment. This is sure to work.
Volker
