### ISSUE TITLE
make failed in Ubuntu 18

### ISSUE THREAD

**Issue by mooerccx** [BrendelGroup/GeneSeqer#6]
hello ，When I installed the software, the following errors occurred, and I didn't find the relevant solutions. I hope you can give us your opinions , Thank you very much

> ccx@DESKTOP-ERKH5PE:~/app/GENESEQER/src$ make linux
make[1]: Entering directory '/home/ccx/app/GENESEQER/src'
gcc -fsigned-char -O2 -Werror -DAN6PLAT -I../include   -c -o DbSuffix.o DbSuffix.c
In file included from DbSuffix.c:62:0:
DbSuffix.c: In function ‘DbSuffixArray’:
../include/platform.h:835:23: error: ignoring return value of ‘fread’, declared with attribute warn_unused_result [-Werror=unused-result]
 #define rdbinf(f,r,n) fread(r,1,n,f) /* Read a binary file */
                       ^~~~~~~~~~~~~~
DbSuffix.c:205:3: note: in expansion of macro ‘rdbinf’
   rdbinf(fpSuffix, Buffer, 1024 * sizeof(LONG));
   ^~~~~~
../include/platform.h:835:23: error: ignoring return value of ‘fread’, declared with attribute warn_unused_result [-Werror=unused-result]
 #define rdbinf(f,r,n) fread(r,1,n,f) /* Read a binary file */
                       ^~~~~~~~~~~~~~
DbSuffix.c:209:7: note: in expansion of macro ‘rdbinf’
       rdbinf(fpSuffix, Buffer, 1024 * sizeof(LONG));
       ^~~~~~
cc1: all warnings being treated as errors
<builtin>: recipe for target 'DbSuffix.o' failed
make[1]: *** [DbSuffix.o] Error 1
make[1]: Leaving directory '/home/ccx/app/GENESEQER/src'
Makefile:33: recipe for target 'linux' failed

**Comment by vpbrendel** [comment]
Current code compiles fine on Ubuntu 18 and 20 as described with "make linux"
